### ISSUE TITLE
Assignment 5 is ready for grading

### ISSUE THREAD

**Issue by mwillisj** [SES-5215-F2020/mwillisjackson-quant#5]
Looking forward to your feedback!

https://ses-5215-f2020.github.io/mwillisjackson-quant/Assignment5

**Comment by c-voulgaris** [comment]
This all looks good. I do like your careful consideration of your preferred model - between two models with nearly the same fit, you selected the one that tests an interesting theory.

That interaction plot is **SUPER** interesting! This is a relationship that totally makes sense, but that I've honestly never seen before. Maybe I'll explore this further in my own research - I'll let you know if I do.
